apiVersion: apps/v1
kind: Deployment
metadata:
  name: skaletor
spec:
  replicas: 1
  selector:
    matchLabels:
      name: skaletor
  template:
    metadata:
      labels:
        name: skaletor
    spec:
      serviceAccountName: skaletor
      containers:
        - name: skaletor
          # Replace this with the built image name
          image: REPLACE_IMAGE
          command:
          - skaletor
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "skaletor"
